plugins {
    id "com.android.application"
}

android {
    namespace "com.acgc.port"
    compileSdk 34

    defaultConfig {
        applicationId "com.acgc.port"
        minSdk 23
        targetSdk 34
        versionCode 2
        versionName "0.2.0"

        externalNativeBuild {
            cmake {
                arguments "-DANDROID_STL=c++_shared"
                abiFilters "armeabi-v7a"
            }
        }
    }

    buildTypes {
        debug {
            debuggable true
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
        }
    }

    sourceSets {
        main {
            java.srcDirs += ["../SDL/android-project/app/src/main/java"]
            assets.srcDirs += ["../../pc/shaders"]
        }
    }

    externalNativeBuild {
        cmake {
            path file("CMakeLists.txt")
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
